### ISSUE TITLE
没有开源啊？

### ISSUE THREAD

**Issue by lllyin** [JarenChow/Janvas#1]
把小星星撤回来了。

**Comment by JarenChow** [comment]
JanvasExamples 有独立的源代码，Janvas 项目之前因为没用npm方式管理，所以只是简单压缩传上去了，格式化一下也是能看明白的

**Comment by JarenChow** [comment]
添加了说明，如果对源码或使用有什么需要的话可以考虑进下讨论群
补充：或者加375379107
